version: '3.1'

services:
  mrscrooge:
    image: dracks/mrscrooge
    container_name: mrscrooge
    depends_on:
      - postgres
    environment:
      DEMOUSER: "user"
      DEMOPWD: "pwd"
    ports:
      - 3333:80

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mrscrooge

