language: python
sudo: true

python:
    - "3.6"
node:
    - "8"

cache:
  directories:
    - "view/node_modules"

addons:
  apt:
    packages:
    - docker

install:
  - pip install -r server/requirements.txt
  - (cd view; rm -rf node_modules/*/.git; npm install)

before_script:
  - (cd server; ./manage.py test)
  - (cd view; npm test)

script:
  - (cd view; npm run build)
  - docker build -t dracks/mrscrooge:latest -f config/sqlite/Dockerfile .
  - docker tag dracks/mrscrooge:latest dracks/mrscrooge:${TRAVIS_TAG:-snapshot}
  - docker build -t dracks/mrscrooge:latest-postgres config/postgres/
  - docker tag dracks/mrscrooge:latest-postgres dracks/mrscrooge:${TRAVIS_TAG:-snapshot}-postgres

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin

deploy:
  provider: script
  script: (
    docker push dracks/mrscrooge:${TRAVIS_TAG:-snapshot} &&
    docker push dracks/mrscrooge:${TRAVIS_TAG:-snapshot}-postgres
    )
  on:
    tags: true