name: mr-scrooge
version: 3.0.0
scripts:
  build:api-models: >-
    openapi-typescript src/@typespec/openapi3/openapi.yaml --output
    src/react-view/api/generated-models.ts
  build:typespec: tsp compile src/typespec --output-dir src
  build:view: NODE_ENV=production webpack --config config/webpack5.config.ts
  start:dev: DEBUG=true ts-node src/main.ts
  lint: eslint 'src/react-view/**/*.{ts,tsx}' --no-warn-ignored
  lint:fix: eslint --fix 'src/react-view/**/*.{ts,tsx}'
  format:fix: prettier --config config/prettierrc --write 'src/react-view/**/*.{ts,tsx}'
  format:typespec: tsp format src/typespec/*.tsp
  test: jest --config config/jest.json
  test:watch: jest --config config/jest.json --watch
  type-check: tsc -p tsconfig.json --noEmit
devDependencies:
  '@eslint/js': ^9.12.0
  '@testing-library/react': ^16.0.1
  '@types/jest': ^29.5.13
  '@types/node': ^22.7.4
  '@types/react': ^18.3.11
  '@types/react-dom': ^18.3.0
  '@typespec/compiler': 0.61.0
  '@typespec/http': 0.61.0
  '@typespec/json-schema': 0.61.0
  '@typespec/openapi': ^0.64.0
  '@typespec/openapi3': 0.61.0
  '@typespec/rest': 0.61.0
  eslint: ^9.11.1
  eslint-config-prettier: ^9.1.0
  eslint-plugin-prettier: ^5.2.1
  eslint-plugin-react: ^7.37.1
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-typescript-sort-keys: ^3.2.0
  eslint-plugin-unicorn: ^56.0.0
  html-webpack-plugin: ^5.6.0
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  jest-fixed-jsdom: ^0.0.9
  msw: ^2.7.0
  node-polyfill-webpack-plugin: ^4.0.0
  openapi-msw: ^1.0.0
  openapi-typescript: ^7.4.1
  sass: ^1.79.4
  sass-loader: ^16.0.2
  ts-jest: ^29.2.5
  ts-loader: ^9.5.1
  ts-node: ^10.9.2
  typescript: ^5.6.2
  typescript-eslint: ^8.8.0
  webpack: ^5.95.0
  webpack-cli: ^5.1.4
dependencies:
  '@types/d3-scale-chromatic': ^3.0.3
  d3-color: ^3.1.0
  d3-interpolate: ^3.0.1
  d3-scale-chromatic: ^3.1.0
  date-fns: ^4.1.0
  factory.ts: ^1.4.1
  grommet: ^2.40.1
  grommet-icons: ^4.12.1
  openapi-fetch: ^0.12.2
  openapi-typescript-fetch: ^2.0.0
  react: ^18.3.1
  react-async-hook: ^4.0.0
  react-dom: ^18.3.1
  react-error-boundary: ^4.0.13
  react-i18next: ^15.0.2
  react-router: ^6.26.2
  react-router-dom: ^6.26.2
  recharts: ^2.13.0
  zod: ^3.23.8
packageManager: pnpm@9.12.0
