name: mr-scrooge
version: 3.0.0
scripts:
  build:api-models: >-
    openapi-typescript src/@typespec/openapi3/openapi.yaml --output
    src/react-view/api/generated-models.ts
  build:typespec: tsp compile src/typespec --output-dir src
  build:view: NODE_ENV=production webpack --config config/webpack5.config.ts
  start:dev: DEBUG=true ts-node src/main.ts
  lint: eslint 'src/react-view/**/*.{ts,tsx}' --no-warn-ignored
  lint:fix: eslint --fix 'src/react-view/**/*.{ts,tsx}'
  format:fix: prettier --config config/prettierrc --write 'src/react-view/**/*.{ts,tsx}'
  format:typespec: tsp format src/typespec/*.tsp
  test: jest --config config/jest.json
  test:watch: jest --config config/jest.json --watch
  type-check: tsc -p tsconfig.json --noEmit
devDependencies:
  '@eslint/js': 9.39.1
  '@testing-library/react': 16.3.0
  '@types/jest': 30.0.0
  '@types/react': 19.2.6
  '@types/node': 24.10.1
  '@types/react-dom': 19.2.3
  '@typespec/compiler': 1.6.0
  '@typespec/http': 1.6.0
  '@typespec/json-schema': 1.6.0
  '@typespec/openapi': 1.6.0
  '@typespec/openapi3': 1.6.0
  '@typespec/rest': 0.76.0
  '@typespec/versioning': ^0.76.0
  eslint: 9.39.1
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-react: 7.37.5
  eslint-plugin-simple-import-sort: 12.1.1
  eslint-plugin-typescript-sort-keys: 3.3.0
  eslint-plugin-unicorn: 62.0.0
  html-webpack-plugin: 5.6.5
  jest: 30.2.0
  jest-environment-jsdom: 30.2.0
  jest-fixed-jsdom: 0.0.11
  msw: 2.7.4
  node-polyfill-webpack-plugin: 4.1.0
  openapi-msw: 2.0.0
  openapi-typescript: 7.10.1
  sass: 1.94.2
  sass-loader: 16.0.6
  ts-jest: 29.4.5
  ts-loader: 9.5.4
  ts-node: 10.9.2
  typescript: 5.9.3
  typescript-eslint: 8.47.0
  webpack: 5.103.0
  webpack-cli: 6.0.1
dependencies:
  '@types/d3-scale-chromatic': 3.1.0
  d3-color: 3.1.0
  d3-interpolate: 3.0.1
  d3-scale-chromatic: 3.1.0
  date-fns: 4.1.0
  factory.ts: 1.4.2
  grommet: 2.51.0
  grommet-icons: 4.14.0
  openapi-fetch: 0.15.0
  openapi-typescript-fetch: 2.2.1
  react: 19.2.0
  react-async-hook: 4.0.0
  react-dom: 19.2.0
  react-error-boundary: 6.0.0
  react-i18next: 16.3.5
  react-router: 7.9.6
  react-router-dom: 7.9.6
  recharts: 3.4.1
  zod: 4.1.12
packageManager: pnpm@10.23.0
