name: mr-scrooge
version: 3.0.0
scripts:
  build:api-models: >-
    openapi-typescript src/@typespec/openapi3/openapi.yaml --output
    src/react-view/api/generated-models.ts
  build:typespec: tsp compile src/typespec --output-dir src
  build:view: NODE_ENV=production webpack --config config/webpack5.config.ts
  start:dev: DEBUG=true ts-node src/main.ts
  lint: eslint 'src/react-view/**/*.{ts,tsx}' --no-warn-ignored
  lint:fix: eslint --fix 'src/react-view/**/*.{ts,tsx}'
  format:fix: prettier --config config/prettierrc --write 'src/react-view/**/*.{ts,tsx}'
  format:typespec: tsp format src/typespec/*.tsp
  test: jest --config config/jest.json
  test:watch: jest --config config/jest.json --watch
  type-check: tsc -p tsconfig.json --noEmit
devDependencies:
  '@eslint/js': 9.24.0
  '@testing-library/react': 16.1.0
  '@types/jest': 29.5.14
  '@types/node': 22.13.14
  '@types/react': 19.1.0
  '@types/react-dom': 19.1.1
  '@typespec/compiler': 0.61.0
  '@typespec/http': 0.61.0
  '@typespec/json-schema': 0.61.0
  '@typespec/openapi': 0.64.0
  '@typespec/openapi3': 0.61.0
  '@typespec/rest': 0.61.0
  eslint: 9.24.0
  eslint-config-prettier: 9.1.0
  eslint-plugin-prettier: 5.2.6
  eslint-plugin-react: 7.37.5
  eslint-plugin-simple-import-sort: 12.1.1
  eslint-plugin-typescript-sort-keys: 3.3.0
  eslint-plugin-unicorn: 56.0.1
  html-webpack-plugin: 5.6.3
  jest: 29.7.0
  jest-environment-jsdom: 29.7.0
  jest-fixed-jsdom: 0.0.9
  msw: 2.7.3
  node-polyfill-webpack-plugin: 4.1.0
  openapi-msw: 1.2.0
  openapi-typescript: 7.6.1
  sass: 1.86.0
  sass-loader: 16.0.5
  ts-jest: 29.3.0
  ts-loader: 9.5.2
  ts-node: 10.9.2
  typescript: 5.8.2
  typescript-eslint: 8.18.0
  webpack: 5.98.0
  webpack-cli: 6.0.1
dependencies:
  '@types/d3-scale-chromatic': 3.1.0
  d3-color: 3.1.0
  d3-interpolate: 3.0.1
  d3-scale-chromatic: 3.1.0
  date-fns: 4.1.0
  factory.ts: 1.4.2
  grommet: 2.46.0
  grommet-icons: 4.12.4
  openapi-fetch: 0.13.5
  openapi-typescript-fetch: 2.1.0
  react: 19.1.0
  react-async-hook: 4.0.0
  react-dom: 19.1.0
  react-error-boundary: 5.0.0
  react-i18next: 15.4.1
  react-router: 7.5.0
  react-router-dom: 7.5.0
  recharts: 2.15.1
  zod: 3.24.2
packageManager: pnpm@10.7.1
