name: mr-scrooge
version: 3.0.0
scripts:
  build:api-models: >-
    openapi-typescript src/@typespec/openapi3/openapi.yaml --output
    src/react-view/api/generated-models.ts
  build:typespec: tsp compile src/typespec --output-dir src
  build:view: NODE_ENV=production webpack --config config/webpack5.config.ts
  start:dev: DEBUG=true ts-node src/main.ts
  lint: eslint 'src/react-view/**/*.{ts,tsx}' --no-warn-ignored
  lint:fix: eslint --fix 'src/react-view/**/*.{ts,tsx}'
  format:fix: prettier --config config/prettierrc --write 'src/react-view/**/*.{ts,tsx}'
  format:typespec: tsp format src/typespec/*.tsp
  test: jest --config config/jest.json
  test:watch: jest --config config/jest.json --watch
  type-check: tsc -p tsconfig.json --noEmit
devDependencies:
  '@eslint/js': 9.32.0
  '@testing-library/react': 16.3.0
  '@types/jest': 30.0.0
  '@types/react': 19.1.8
  '@types/node': 22.16.3
  '@types/react-dom': 19.1.6
  '@typespec/compiler': 1.1.0
  '@typespec/http': 1.1.0
  '@typespec/json-schema': 1.1.0
  '@typespec/openapi': 1.1.0
  '@typespec/openapi3': 1.1.0
  '@typespec/rest': 0.71.0
  '@typespec/versioning': ^0.71.0
  eslint: 9.32.0
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.3
  eslint-plugin-react: 7.37.5
  eslint-plugin-simple-import-sort: 12.1.1
  eslint-plugin-typescript-sort-keys: 3.3.0
  eslint-plugin-unicorn: 59.0.1
  html-webpack-plugin: 5.6.3
  jest: 30.0.4
  jest-environment-jsdom: 30.0.4
  jest-fixed-jsdom: 0.0.9
  msw: 2.7.4
  node-polyfill-webpack-plugin: 4.1.0
  openapi-msw: 1.2.0
  openapi-typescript: 7.8.0
  sass: 1.89.2
  sass-loader: 16.0.5
  ts-jest: 29.4.0
  ts-loader: 9.5.2
  ts-node: 10.9.2
  typescript: 5.8.3
  typescript-eslint: 8.36.0
  webpack: 5.100.1
  webpack-cli: 6.0.1
dependencies:
  '@types/d3-scale-chromatic': 3.1.0
  d3-color: 3.1.0
  d3-interpolate: 3.0.1
  d3-scale-chromatic: 3.1.0
  date-fns: 4.1.0
  factory.ts: 1.4.2
  grommet: 2.47.0
  grommet-icons: 4.14.0
  openapi-fetch: 0.14.0
  openapi-typescript-fetch: 2.2.1
  react: 19.1.1
  react-async-hook: 4.0.0
  react-dom: 19.1.1
  react-error-boundary: 6.0.0
  react-i18next: 15.6.1
  react-router: 7.7.1
  react-router-dom: 7.7.1
  recharts: 3.1.0
  zod: 4.0.5
packageManager: pnpm@10.13.1
