allowBuilds:
  '@parcel/watcher': set this to true or false
  msw: set this to true or false
  node-sass: set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - msw
  - node-sass
  - unrs-resolver
