# Generated by Django 2.0.1 on 2018-05-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_tag_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuestotag',
            name='raw_data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='importer.RawDataSource'),
        ),
    ]
