# Generated by Django 2.0.8 on 2018-11-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('management', '0004_auto_20181123_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuestotag',
            name='raw_data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.RawDataSource'),
        ),
    ]
