# Generated by Django 2.0.10 on 2019-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190210_1703'),
        ('management', '0005_auto_20181123_0718'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valuestotag',
            unique_together={('raw_data_source', 'tag')},
        ),
        migrations.AddIndex(
            model_name='valuestotag',
            index=models.Index(fields=['raw_data_source'], name='rds_idx'),
        ),
        migrations.AddIndex(
            model_name='valuestotag',
            index=models.Index(fields=['tag'], name='tag_idx'),
        ),
    ]
