//
// Account.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** AccountSerializer. */
public struct Account: Sendable, Codable, Hashable {

    /** The ID of this Account, used to refer to this account in other API calls. */
    public var id: UUID?
    /** The date & time at which the account object was created. */
    public var created: Date?
    /** The date & time at which the account object was last accessed. */
    public var lastAccessed: Date?
    /** The Account IBAN */
    public var iban: String?
    /** The Account BBAN */
    public var bban: String?
    /** The processing status of this account. */
    public var status: String?
    /** The ASPSP associated with this account. */
    public var institutionId: String?
    /** The name of the account owner. */
    public var ownerName: String?
    /** The name of account. */
    public var name: String?

    public init(id: UUID? = nil, created: Date? = nil, lastAccessed: Date? = nil, iban: String? = nil, bban: String? = nil, status: String? = nil, institutionId: String? = nil, ownerName: String? = nil, name: String? = nil) {
        self.id = id
        self.created = created
        self.lastAccessed = lastAccessed
        self.iban = iban
        self.bban = bban
        self.status = status
        self.institutionId = institutionId
        self.ownerName = ownerName
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case created
        case lastAccessed = "last_accessed"
        case iban
        case bban
        case status
        case institutionId = "institution_id"
        case ownerName = "owner_name"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(lastAccessed, forKey: .lastAccessed)
        try container.encodeIfPresent(iban, forKey: .iban)
        try container.encodeIfPresent(bban, forKey: .bban)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(institutionId, forKey: .institutionId)
        try container.encodeIfPresent(ownerName, forKey: .ownerName)
        try container.encodeIfPresent(name, forKey: .name)
    }
}


extension Account: Identifiable {}
