//
// AdditionalAccountDataSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** AdditionalAccountDataSchema. */
public struct AdditionalAccountDataSchema: Sendable, Codable, Hashable {

    /** secondaryIdentification */
    public var secondaryIdentification: String?

    public init(secondaryIdentification: String? = nil) {
        self.secondaryIdentification = secondaryIdentification
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case secondaryIdentification
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(secondaryIdentification, forKey: .secondaryIdentification)
    }
}

