//
// BankTransaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** BankTransactionSerializer. */
public struct BankTransaction: Sendable, Codable, Hashable {

    public var booked: [TransactionSchema]
    public var pending: [TransactionSchema]?

    public init(booked: [TransactionSchema], pending: [TransactionSchema]? = nil) {
        self.booked = booked
        self.pending = pending
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case booked
        case pending
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(booked, forKey: .booked)
        try container.encodeIfPresent(pending, forKey: .pending)
    }
}

