//
// CurrencyExchangeSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** CurrencyExchangeSchema. */
public struct CurrencyExchangeSchema: Sendable, Codable, Hashable {

    /** sourceCurrency */
    public var sourceCurrency: String?
    /** exchangeRate */
    public var exchangeRate: String?
    /** unitCurrency */
    public var unitCurrency: String?
    /** targetCurrency */
    public var targetCurrency: String?
    /** quotationDate */
    public var quotationDate: String?
    /** contractIdentification */
    public var contractIdentification: String?

    public init(sourceCurrency: String? = nil, exchangeRate: String? = nil, unitCurrency: String? = nil, targetCurrency: String? = nil, quotationDate: String? = nil, contractIdentification: String? = nil) {
        self.sourceCurrency = sourceCurrency
        self.exchangeRate = exchangeRate
        self.unitCurrency = unitCurrency
        self.targetCurrency = targetCurrency
        self.quotationDate = quotationDate
        self.contractIdentification = contractIdentification
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sourceCurrency
        case exchangeRate
        case unitCurrency
        case targetCurrency
        case quotationDate
        case contractIdentification
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sourceCurrency, forKey: .sourceCurrency)
        try container.encodeIfPresent(exchangeRate, forKey: .exchangeRate)
        try container.encodeIfPresent(unitCurrency, forKey: .unitCurrency)
        try container.encodeIfPresent(targetCurrency, forKey: .targetCurrency)
        try container.encodeIfPresent(quotationDate, forKey: .quotationDate)
        try container.encodeIfPresent(contractIdentification, forKey: .contractIdentification)
    }
}

