//
// EndUserAgreement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Represents an end-user agreement. */
public struct EndUserAgreement: Sendable, Codable, Hashable {

    public static let maxHistoricalDaysRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 730, exclusiveMaximum: false, multipleOf: nil)
    public static let accessValidForDaysRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 730, exclusiveMaximum: false, multipleOf: nil)
    /** The ID of this End User Agreement, used to refer to this end user agreement in other API calls. */
    public var id: UUID?
    /** The date & time at which the end user agreement was created. */
    public var created: Date?
    /** an Institution ID for this EUA */
    public var institutionId: String
    /** Maximum number of days of transaction data to retrieve. */
    public var maxHistoricalDays: Int? = 90
    /** Number of days from acceptance that the access can be used. */
    public var accessValidForDays: Int? = 90
    /** Array containing one or several values of ['balances', 'details', 'transactions'] */
    public var accessScope: [JSONValue]?
    /** The date & time at which the end user accepted the agreement. */
    public var accepted: Date?
    /** if this agreement can be extended. Supported by GB banks only. */
    public var reconfirmation: Bool? = false

    public init(id: UUID? = nil, created: Date? = nil, institutionId: String, maxHistoricalDays: Int? = 90, accessValidForDays: Int? = 90, accessScope: [JSONValue]? = nil, accepted: Date? = nil, reconfirmation: Bool? = false) {
        self.id = id
        self.created = created
        self.institutionId = institutionId
        self.maxHistoricalDays = maxHistoricalDays
        self.accessValidForDays = accessValidForDays
        self.accessScope = accessScope
        self.accepted = accepted
        self.reconfirmation = reconfirmation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case created
        case institutionId = "institution_id"
        case maxHistoricalDays = "max_historical_days"
        case accessValidForDays = "access_valid_for_days"
        case accessScope = "access_scope"
        case accepted
        case reconfirmation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encode(institutionId, forKey: .institutionId)
        try container.encodeIfPresent(maxHistoricalDays, forKey: .maxHistoricalDays)
        try container.encodeIfPresent(accessValidForDays, forKey: .accessValidForDays)
        try container.encodeIfPresent(accessScope, forKey: .accessScope)
        try container.encodeIfPresent(accepted, forKey: .accepted)
        try container.encodeIfPresent(reconfirmation, forKey: .reconfirmation)
    }
}


extension EndUserAgreement: Identifiable {}
