//
// JWTObtainPairRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Obtain JWT pair. */
public struct JWTObtainPairRequest: Sendable, Codable, Hashable {

    public static let secretIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let secretKeyRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Secret id from /user-secrets/ */
    public var secretId: String
    /** Secret key from /user-secrets/ */
    public var secretKey: String

    public init(secretId: String, secretKey: String) {
        self.secretId = secretId
        self.secretKey = secretKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case secretId = "secret_id"
        case secretKey = "secret_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(secretId, forKey: .secretId)
        try container.encode(secretKey, forKey: .secretKey)
    }
}

