//
// RequisitionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** RequisitionSerializer. */
public struct RequisitionRequest: Sendable, Codable, Hashable {

    public static let redirectRule = StringRule(minLength: 1, maxLength: 1024, pattern: nil)
    public static let institutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let referenceRule = StringRule(minLength: 1, maxLength: 256, pattern: nil)
    public static let userLanguageRule = StringRule(minLength: 1, maxLength: 5, pattern: nil)
    public static let ssnRule = StringRule(minLength: nil, maxLength: 64, pattern: nil)
    /** redirect URL to your application after end-user authorization with ASPSP */
    public var redirect: String?
    /** an Institution ID for this Requisition */
    public var institutionId: String
    /** EUA associated with this requisition */
    public var agreement: UUID?
    /** additional ID to identify the end user */
    public var reference: String?
    /** A two-letter country code (ISO 639-1) */
    public var userLanguage: String?
    /** optional SSN field to verify ownership of the account */
    public var ssn: String?
    /** option to enable account selection view for the end user */
    public var accountSelection: Bool? = false
    /** enable redirect back to the client after account list received */
    public var redirectImmediate: Bool? = false

    public init(redirect: String?, institutionId: String, agreement: UUID? = nil, reference: String? = nil, userLanguage: String? = nil, ssn: String? = nil, accountSelection: Bool? = false, redirectImmediate: Bool? = false) {
        self.redirect = redirect
        self.institutionId = institutionId
        self.agreement = agreement
        self.reference = reference
        self.userLanguage = userLanguage
        self.ssn = ssn
        self.accountSelection = accountSelection
        self.redirectImmediate = redirectImmediate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redirect
        case institutionId = "institution_id"
        case agreement
        case reference
        case userLanguage = "user_language"
        case ssn
        case accountSelection = "account_selection"
        case redirectImmediate = "redirect_immediate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(redirect, forKey: .redirect)
        try container.encode(institutionId, forKey: .institutionId)
        try container.encodeIfPresent(agreement, forKey: .agreement)
        try container.encodeIfPresent(reference, forKey: .reference)
        try container.encodeIfPresent(userLanguage, forKey: .userLanguage)
        try container.encodeIfPresent(ssn, forKey: .ssn)
        try container.encodeIfPresent(accountSelection, forKey: .accountSelection)
        try container.encodeIfPresent(redirectImmediate, forKey: .redirectImmediate)
    }
}

