//
// TransactionSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** TransactionSchema. */
public struct TransactionSchema: Sendable, Codable, Hashable {

    /** transactionId */
    public var transactionId: String?
    /** entryReference */
    public var entryReference: String?
    /** endToEndId */
    public var endToEndId: String?
    /** mandateId */
    public var mandateId: String?
    /** checkId */
    public var checkId: String?
    /** creditorId */
    public var creditorId: String?
    /** bookingDate */
    public var bookingDate: String?
    /** valueDate */
    public var valueDate: String?
    /** bookingDateTime */
    public var bookingDateTime: String?
    /** valueDateTime */
    public var valueDateTime: String?
    /** transactionAmount */
    public var transactionAmount: TransactionAmountSchema
    public var currencyExchange: [CurrencyExchangeSchema]?
    /** creditorName */
    public var creditorName: String?
    /** creditorAccount */
    public var creditorAccount: AccountSchema?
    /** ultimateCreditor */
    public var ultimateCreditor: String?
    /** debtorName */
    public var debtorName: String?
    /** debtorAccount */
    public var debtorAccount: AccountSchema?
    /** ultimateDebtor */
    public var ultimateDebtor: String?
    /** remittanceInformationUnstructured */
    public var remittanceInformationUnstructured: String?
    /** remittanceInformationUnstructuredArray */
    public var remittanceInformationUnstructuredArray: [String]?
    /** remittanceInformationStructured */
    public var remittanceInformationStructured: String?
    /** remittanceInformationStructuredArray */
    public var remittanceInformationStructuredArray: [String]?
    /** additionalInformation */
    public var additionalInformation: String?
    /** purposeCode */
    public var purposeCode: String?
    /** bankTransactionCode */
    public var bankTransactionCode: String?
    /** proprietaryBankTransactionCode */
    public var proprietaryBankTransactionCode: String?
    /** internalTransactionId */
    public var internalTransactionId: String?
    /** balanceAfterTransaction */
    public var balanceAfterTransaction: BalanceAfterTransactionSchema?

    public init(transactionId: String? = nil, entryReference: String? = nil, endToEndId: String? = nil, mandateId: String? = nil, checkId: String? = nil, creditorId: String? = nil, bookingDate: String? = nil, valueDate: String? = nil, bookingDateTime: String? = nil, valueDateTime: String? = nil, transactionAmount: TransactionAmountSchema, currencyExchange: [CurrencyExchangeSchema]? = nil, creditorName: String? = nil, creditorAccount: AccountSchema? = nil, ultimateCreditor: String? = nil, debtorName: String? = nil, debtorAccount: AccountSchema? = nil, ultimateDebtor: String? = nil, remittanceInformationUnstructured: String? = nil, remittanceInformationUnstructuredArray: [String]? = nil, remittanceInformationStructured: String? = nil, remittanceInformationStructuredArray: [String]? = nil, additionalInformation: String? = nil, purposeCode: String? = nil, bankTransactionCode: String? = nil, proprietaryBankTransactionCode: String? = nil, internalTransactionId: String? = nil, balanceAfterTransaction: BalanceAfterTransactionSchema? = nil) {
        self.transactionId = transactionId
        self.entryReference = entryReference
        self.endToEndId = endToEndId
        self.mandateId = mandateId
        self.checkId = checkId
        self.creditorId = creditorId
        self.bookingDate = bookingDate
        self.valueDate = valueDate
        self.bookingDateTime = bookingDateTime
        self.valueDateTime = valueDateTime
        self.transactionAmount = transactionAmount
        self.currencyExchange = currencyExchange
        self.creditorName = creditorName
        self.creditorAccount = creditorAccount
        self.ultimateCreditor = ultimateCreditor
        self.debtorName = debtorName
        self.debtorAccount = debtorAccount
        self.ultimateDebtor = ultimateDebtor
        self.remittanceInformationUnstructured = remittanceInformationUnstructured
        self.remittanceInformationUnstructuredArray = remittanceInformationUnstructuredArray
        self.remittanceInformationStructured = remittanceInformationStructured
        self.remittanceInformationStructuredArray = remittanceInformationStructuredArray
        self.additionalInformation = additionalInformation
        self.purposeCode = purposeCode
        self.bankTransactionCode = bankTransactionCode
        self.proprietaryBankTransactionCode = proprietaryBankTransactionCode
        self.internalTransactionId = internalTransactionId
        self.balanceAfterTransaction = balanceAfterTransaction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionId
        case entryReference
        case endToEndId
        case mandateId
        case checkId
        case creditorId
        case bookingDate
        case valueDate
        case bookingDateTime
        case valueDateTime
        case transactionAmount
        case currencyExchange
        case creditorName
        case creditorAccount
        case ultimateCreditor
        case debtorName
        case debtorAccount
        case ultimateDebtor
        case remittanceInformationUnstructured
        case remittanceInformationUnstructuredArray
        case remittanceInformationStructured
        case remittanceInformationStructuredArray
        case additionalInformation
        case purposeCode
        case bankTransactionCode
        case proprietaryBankTransactionCode
        case internalTransactionId
        case balanceAfterTransaction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(transactionId, forKey: .transactionId)
        try container.encodeIfPresent(entryReference, forKey: .entryReference)
        try container.encodeIfPresent(endToEndId, forKey: .endToEndId)
        try container.encodeIfPresent(mandateId, forKey: .mandateId)
        try container.encodeIfPresent(checkId, forKey: .checkId)
        try container.encodeIfPresent(creditorId, forKey: .creditorId)
        try container.encodeIfPresent(bookingDate, forKey: .bookingDate)
        try container.encodeIfPresent(valueDate, forKey: .valueDate)
        try container.encodeIfPresent(bookingDateTime, forKey: .bookingDateTime)
        try container.encodeIfPresent(valueDateTime, forKey: .valueDateTime)
        try container.encode(transactionAmount, forKey: .transactionAmount)
        try container.encodeIfPresent(currencyExchange, forKey: .currencyExchange)
        try container.encodeIfPresent(creditorName, forKey: .creditorName)
        try container.encodeIfPresent(creditorAccount, forKey: .creditorAccount)
        try container.encodeIfPresent(ultimateCreditor, forKey: .ultimateCreditor)
        try container.encodeIfPresent(debtorName, forKey: .debtorName)
        try container.encodeIfPresent(debtorAccount, forKey: .debtorAccount)
        try container.encodeIfPresent(ultimateDebtor, forKey: .ultimateDebtor)
        try container.encodeIfPresent(remittanceInformationUnstructured, forKey: .remittanceInformationUnstructured)
        try container.encodeIfPresent(remittanceInformationUnstructuredArray, forKey: .remittanceInformationUnstructuredArray)
        try container.encodeIfPresent(remittanceInformationStructured, forKey: .remittanceInformationStructured)
        try container.encodeIfPresent(remittanceInformationStructuredArray, forKey: .remittanceInformationStructuredArray)
        try container.encodeIfPresent(additionalInformation, forKey: .additionalInformation)
        try container.encodeIfPresent(purposeCode, forKey: .purposeCode)
        try container.encodeIfPresent(bankTransactionCode, forKey: .bankTransactionCode)
        try container.encodeIfPresent(proprietaryBankTransactionCode, forKey: .proprietaryBankTransactionCode)
        try container.encodeIfPresent(internalTransactionId, forKey: .internalTransactionId)
        try container.encodeIfPresent(balanceAfterTransaction, forKey: .balanceAfterTransaction)
    }
}

