version: '3.1'

services:
  mrscrooge:
    image: dracks/mrscrooge:latest
    container_name: mrscrooge
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://postgres:postgres@postgres/mrscrooge
      DEMO: true
      DEMO_USER: user
      DEMO_PWD: pwd
    ports:
      - 3333:8080

  postgres:
    image: postgres:latest
    container_name: mrscrooge_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mrscrooge

