version: '3.1'

services:
    mrscrooge:
        image: dracks/mrscrooge
        container_name: mrscrooge
        environment:
          DB_URL: sqlite://./db.sqlite
        ports:
            - 333:8080

