version: '3.1'

services:
    mrscrooge:
        image: dracks/mrscrooge
        container_name: mrscrooge
        environment:
          DB_URL: sqlite://./db.sqlite
          DEMO: true
          DEMO_DATA: true
        ports:
            - 3333:8080

