# Generated by Django 2.0.8 on 2018-11-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('importer', '0005_auto_20181123_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreportrow',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.RawDataSource'),
        ),
    ]
