//
// AccountSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** AccountSchema. */
public struct AccountSchema: Sendable, Codable, Hashable {

    /** iban */
    public var iban: String?
    /** bban */
    public var bban: String?
    /** pan */
    public var pan: String?
    /** maskedPan */
    public var maskedPan: String?
    /** msisdn */
    public var msisdn: String?
    /** currency */
    public var currency: String?

    public init(iban: String? = nil, bban: String? = nil, pan: String? = nil, maskedPan: String? = nil, msisdn: String? = nil, currency: String? = nil) {
        self.iban = iban
        self.bban = bban
        self.pan = pan
        self.maskedPan = maskedPan
        self.msisdn = msisdn
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case iban
        case bban
        case pan
        case maskedPan
        case msisdn
        case currency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(iban, forKey: .iban)
        try container.encodeIfPresent(bban, forKey: .bban)
        try container.encodeIfPresent(pan, forKey: .pan)
        try container.encodeIfPresent(maskedPan, forKey: .maskedPan)
        try container.encodeIfPresent(msisdn, forKey: .msisdn)
        try container.encodeIfPresent(currency, forKey: .currency)
    }
}

