//
// AccountDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** AccountDetailSerializer. */
public struct AccountDetail: Sendable, Content, Hashable {

    /** account */
    public var account: DetailSchema

    public init(account: DetailSchema) {
        self.account = account
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
    }
}

