//
// AccountBalance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** AccountBalanceSerializer. */
public struct AccountBalance: Sendable, Content, Hashable {

    public var balances: [BalanceSchema]?

    public init(balances: [BalanceSchema]? = nil) {
        self.balances = balances
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case balances
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(balances, forKey: .balances)
    }
}

