//
// AccountTransactions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** AccountTransactionsSerializer. */
public struct AccountTransactions: Sendable, Content, Hashable {

    /** transactions */
    public var transactions: BankTransaction
    /** The last time the account transactions were updated */
    public var lastUpdated: Date?

    public init(transactions: BankTransaction, lastUpdated: Date? = nil) {
        self.transactions = transactions
        self.lastUpdated = lastUpdated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactions
        case lastUpdated = "last_updated"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transactions, forKey: .transactions)
        try container.encodeIfPresent(lastUpdated, forKey: .lastUpdated)
    }
}

