//
// BalanceAmountSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** BalanceAmountSchema. */
public struct BalanceAmountSchema: Sendable, Content, Hashable {

    /** amount */
    public var amount: String
    /** currency */
    public var currency: String

    public init(amount: String, currency: String) {
        self.amount = amount
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case currency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(currency, forKey: .currency)
    }
}

