//
// BalanceAfterTransactionSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** BalanceAfterTransactionSchema. */
public struct BalanceAfterTransactionSchema: Sendable, Content, Hashable {

    /** balanceAmount */
    public var balanceAmount: TransactionAmountSchema
    /** balanceType */
    public var balanceType: String

    public init(balanceAmount: TransactionAmountSchema, balanceType: String) {
        self.balanceAmount = balanceAmount
        self.balanceType = balanceType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case balanceAmount
        case balanceType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(balanceAmount, forKey: .balanceAmount)
        try container.encode(balanceType, forKey: .balanceType)
    }
}

