//
// BalanceSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** BalanceSchema. */
public struct BalanceSchema: Sendable, Codable, Hashable {

    /** balanceAmount */
    public var balanceAmount: BalanceAmountSchema
    /** balanceType */
    public var balanceType: String
    /** creditLimitIncluded */
    public var creditLimitIncluded: Bool?
    /** lastChangeDateTime */
    public var lastChangeDateTime: String?
    /** referenceDate */
    public var referenceDate: String?
    /** lastCommittedTransaction */
    public var lastCommittedTransaction: String?

    public init(balanceAmount: BalanceAmountSchema, balanceType: String, creditLimitIncluded: Bool? = nil, lastChangeDateTime: String? = nil, referenceDate: String? = nil, lastCommittedTransaction: String? = nil) {
        self.balanceAmount = balanceAmount
        self.balanceType = balanceType
        self.creditLimitIncluded = creditLimitIncluded
        self.lastChangeDateTime = lastChangeDateTime
        self.referenceDate = referenceDate
        self.lastCommittedTransaction = lastCommittedTransaction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case balanceAmount
        case balanceType
        case creditLimitIncluded
        case lastChangeDateTime
        case referenceDate
        case lastCommittedTransaction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(balanceAmount, forKey: .balanceAmount)
        try container.encode(balanceType, forKey: .balanceType)
        try container.encodeIfPresent(creditLimitIncluded, forKey: .creditLimitIncluded)
        try container.encodeIfPresent(lastChangeDateTime, forKey: .lastChangeDateTime)
        try container.encodeIfPresent(referenceDate, forKey: .referenceDate)
        try container.encodeIfPresent(lastCommittedTransaction, forKey: .lastCommittedTransaction)
    }
}

