//
// DetailSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** DetailSchema. */
public struct DetailSchema: Sendable, Content, Hashable {

    /** resourceId */
    public var resourceId: String?
    /** iban */
    public var iban: String?
    /** bban */
    public var bban: String?
    /** SortCodeAccountNumber returned by some UK banks (6 digit Sort Code and 8 digit Account Number) */
    public var scan: String?
    /** msisdn */
    public var msisdn: String?
    /** currency */
    public var currency: String?
    /** ownerName */
    public var ownerName: String?
    /** name */
    public var name: String?
    /** displayName */
    public var displayName: String?
    /** product */
    public var product: String?
    /** cashAccountType */
    public var cashAccountType: String?
    /** status */
    public var status: String?
    /** bic */
    public var bic: String?
    /** linkedAccounts */
    public var linkedAccounts: String?
    /** maskedPan */
    public var maskedPan: String?
    /** usage */
    public var usage: String?
    /** details */
    public var details: String?
    /** ownerAddressUnstructured */
    public var ownerAddressUnstructured: [String]?
    /** ownerAddressStructured */
    public var ownerAddressStructured: OwnerAddressStructuredSchema?
    /** additionalAccountData used for information that is outside of Berlin Group specification, such as bank or country-specific fields */
    public var additionalAccountData: AdditionalAccountDataSchema?

    public init(resourceId: String? = nil, iban: String? = nil, bban: String? = nil, scan: String? = nil, msisdn: String? = nil, currency: String? = nil, ownerName: String? = nil, name: String? = nil, displayName: String? = nil, product: String? = nil, cashAccountType: String? = nil, status: String? = nil, bic: String? = nil, linkedAccounts: String? = nil, maskedPan: String? = nil, usage: String? = nil, details: String? = nil, ownerAddressUnstructured: [String]? = nil, ownerAddressStructured: OwnerAddressStructuredSchema? = nil, additionalAccountData: AdditionalAccountDataSchema? = nil) {
        self.resourceId = resourceId
        self.iban = iban
        self.bban = bban
        self.scan = scan
        self.msisdn = msisdn
        self.currency = currency
        self.ownerName = ownerName
        self.name = name
        self.displayName = displayName
        self.product = product
        self.cashAccountType = cashAccountType
        self.status = status
        self.bic = bic
        self.linkedAccounts = linkedAccounts
        self.maskedPan = maskedPan
        self.usage = usage
        self.details = details
        self.ownerAddressUnstructured = ownerAddressUnstructured
        self.ownerAddressStructured = ownerAddressStructured
        self.additionalAccountData = additionalAccountData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resourceId
        case iban
        case bban
        case scan
        case msisdn
        case currency
        case ownerName
        case name
        case displayName
        case product
        case cashAccountType
        case status
        case bic
        case linkedAccounts
        case maskedPan
        case usage
        case details
        case ownerAddressUnstructured
        case ownerAddressStructured
        case additionalAccountData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(resourceId, forKey: .resourceId)
        try container.encodeIfPresent(iban, forKey: .iban)
        try container.encodeIfPresent(bban, forKey: .bban)
        try container.encodeIfPresent(scan, forKey: .scan)
        try container.encodeIfPresent(msisdn, forKey: .msisdn)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(ownerName, forKey: .ownerName)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(product, forKey: .product)
        try container.encodeIfPresent(cashAccountType, forKey: .cashAccountType)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(bic, forKey: .bic)
        try container.encodeIfPresent(linkedAccounts, forKey: .linkedAccounts)
        try container.encodeIfPresent(maskedPan, forKey: .maskedPan)
        try container.encodeIfPresent(usage, forKey: .usage)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encodeIfPresent(ownerAddressUnstructured, forKey: .ownerAddressUnstructured)
        try container.encodeIfPresent(ownerAddressStructured, forKey: .ownerAddressStructured)
        try container.encodeIfPresent(additionalAccountData, forKey: .additionalAccountData)
    }
}

