//
// EndUserAgreementRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** Represents an end-user agreement. */
public struct EndUserAgreementRequest: Sendable, Content, Hashable {

    public static let institutionIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let maxHistoricalDaysRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 730, exclusiveMaximum: false, multipleOf: nil)
    public static let accessValidForDaysRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 730, exclusiveMaximum: false, multipleOf: nil)
    /** an Institution ID for this EUA */
    public var institutionId: String
    /** Maximum number of days of transaction data to retrieve. */
    public var maxHistoricalDays: Int? = 90
    /** Number of days from acceptance that the access can be used. */
    public var accessValidForDays: Int? = 90
    /** Array containing one or several values of ['balances', 'details', 'transactions'] */
    public var accessScope: [JSONValue]?
    /** if this agreement can be extended. Supported by GB banks only. */
    public var reconfirmation: Bool? = false

    public init(institutionId: String, maxHistoricalDays: Int? = 90, accessValidForDays: Int? = 90, accessScope: [JSONValue]? = nil, reconfirmation: Bool? = false) {
        self.institutionId = institutionId
        self.maxHistoricalDays = maxHistoricalDays
        self.accessValidForDays = accessValidForDays
        self.accessScope = accessScope
        self.reconfirmation = reconfirmation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case institutionId = "institution_id"
        case maxHistoricalDays = "max_historical_days"
        case accessValidForDays = "access_valid_for_days"
        case accessScope = "access_scope"
        case reconfirmation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(institutionId, forKey: .institutionId)
        try container.encodeIfPresent(maxHistoricalDays, forKey: .maxHistoricalDays)
        try container.encodeIfPresent(accessValidForDays, forKey: .accessValidForDays)
        try container.encodeIfPresent(accessScope, forKey: .accessScope)
        try container.encodeIfPresent(reconfirmation, forKey: .reconfirmation)
    }
}

