//
// EnduserAcceptanceDetailsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** Represents end-user details. */
public struct EnduserAcceptanceDetailsRequest: Sendable, Content, Hashable {

    public static let userAgentRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let ipAddressRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var userAgent: String
    public var ipAddress: String

    public init(userAgent: String, ipAddress: String) {
        self.userAgent = userAgent
        self.ipAddress = ipAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userAgent = "user_agent"
        case ipAddress = "ip_address"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userAgent, forKey: .userAgent)
        try container.encode(ipAddress, forKey: .ipAddress)
    }
}

