//
// Integration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** Represents an Integration. */
public struct Integration: Sendable, Content, Hashable {

    public var id: String
    public var name: String
    public var bic: String?
    public var transactionTotalDays: String? = "90"
    public var maxAccessValidForDays: String?
    public var maxAccessValidForDaysReconfirmation: String?
    public var countries: [String]
    public var logo: String

    public init(id: String, name: String, bic: String? = nil, transactionTotalDays: String? = "90", maxAccessValidForDays: String? = nil, maxAccessValidForDaysReconfirmation: String? = nil, countries: [String], logo: String) {
        self.id = id
        self.name = name
        self.bic = bic
        self.transactionTotalDays = transactionTotalDays
        self.maxAccessValidForDays = maxAccessValidForDays
        self.maxAccessValidForDaysReconfirmation = maxAccessValidForDaysReconfirmation
        self.countries = countries
        self.logo = logo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case bic
        case transactionTotalDays = "transaction_total_days"
        case maxAccessValidForDays = "max_access_valid_for_days"
        case maxAccessValidForDaysReconfirmation = "max_access_valid_for_days_reconfirmation"
        case countries
        case logo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(bic, forKey: .bic)
        try container.encodeIfPresent(transactionTotalDays, forKey: .transactionTotalDays)
        try container.encodeIfPresent(maxAccessValidForDays, forKey: .maxAccessValidForDays)
        try container.encodeIfPresent(maxAccessValidForDaysReconfirmation, forKey: .maxAccessValidForDaysReconfirmation)
        try container.encode(countries, forKey: .countries)
        try container.encode(logo, forKey: .logo)
    }
}


extension Integration: Identifiable {}
