//
// JWTRefreshRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Refresh access token. */
public struct JWTRefreshRequest: Sendable, Codable, Hashable {

    public static let refreshRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var refresh: String

    public init(refresh: String) {
        self.refresh = refresh
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case refresh
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(refresh, forKey: .refresh)
    }
}

