//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

public struct ModelErrorResponse: Sendable, Content, Hashable {

    public var summary: String
    public var detail: String
    public var type: String?
    public var statusCode: Int

    public init(summary: String, detail: String, type: String? = nil, statusCode: Int) {
        self.summary = summary
        self.detail = detail
        self.type = type
        self.statusCode = statusCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case summary
        case detail
        case type
        case statusCode = "status_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(summary, forKey: .summary)
        try container.encode(detail, forKey: .detail)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(statusCode, forKey: .statusCode)
    }
}

