//
// OwnerAddressStructuredSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** OwnerAddressStructuredSchema. */
public struct OwnerAddressStructuredSchema: Sendable, Codable, Hashable {

    /** streetName */
    public var streetName: String?
    /** buildingNumber */
    public var buildingNumber: String?
    /** townName */
    public var townName: String?
    /** postCode */
    public var postCode: String?
    /** country */
    public var country: String?

    public init(streetName: String? = nil, buildingNumber: String? = nil, townName: String? = nil, postCode: String? = nil, country: String? = nil) {
        self.streetName = streetName
        self.buildingNumber = buildingNumber
        self.townName = townName
        self.postCode = postCode
        self.country = country
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case streetName
        case buildingNumber
        case townName
        case postCode
        case country
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(streetName, forKey: .streetName)
        try container.encodeIfPresent(buildingNumber, forKey: .buildingNumber)
        try container.encodeIfPresent(townName, forKey: .townName)
        try container.encodeIfPresent(postCode, forKey: .postCode)
        try container.encodeIfPresent(country, forKey: .country)
    }
}

