//
// ReconfirmationRetrieveRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** EUA reconfirmation. */
public struct ReconfirmationRetrieveRequest: Sendable, Codable, Hashable {

    public static let redirectRule = StringRule(minLength: nil, maxLength: 1024, pattern: nil)
    /** Optional redirect URL for reconfirmation to override requisition's redirect. */
    public var redirect: String?

    public init(redirect: String? = nil) {
        self.redirect = redirect
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redirect
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(redirect, forKey: .redirect)
    }
}

