//
// ReconfirmationRetrieve.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** EUA reconfirmation. */
public struct ReconfirmationRetrieve: Sendable, Content, Hashable {

    public static let redirectRule = StringRule(minLength: nil, maxLength: 1024, pattern: nil)
    /** Reconfirmation URL to be provided to PSU. */
    public var reconfirmationUrl: String?
    /** Reconfirmation creation time */
    public var created: Date?
    /** Datetime from when PSU will be able to access reconfirmation URL. */
    public var urlValidFrom: Date?
    /** Datetime until when PSU will be able to access reconfirmation URL. */
    public var urlValidTo: Date?
    /** Optional redirect URL for reconfirmation to override requisition's redirect. */
    public var redirect: String?
    /** Last time when reconfirmation was accessed (this does not mean that it was accessed by PSU). */
    public var lastAccessed: Date?
    /** Last time reconfirmation was submitted (it can be submitted multiple times). */
    public var lastSubmitted: Date?
    /** Dictionary of accounts and their reconfirm and reject timestamps */
    public var accounts: JSONValue?

    public init(reconfirmationUrl: String? = nil, created: Date? = nil, urlValidFrom: Date? = nil, urlValidTo: Date? = nil, redirect: String? = nil, lastAccessed: Date? = nil, lastSubmitted: Date? = nil, accounts: JSONValue? = nil) {
        self.reconfirmationUrl = reconfirmationUrl
        self.created = created
        self.urlValidFrom = urlValidFrom
        self.urlValidTo = urlValidTo
        self.redirect = redirect
        self.lastAccessed = lastAccessed
        self.lastSubmitted = lastSubmitted
        self.accounts = accounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reconfirmationUrl = "reconfirmation_url"
        case created
        case urlValidFrom = "url_valid_from"
        case urlValidTo = "url_valid_to"
        case redirect
        case lastAccessed = "last_accessed"
        case lastSubmitted = "last_submitted"
        case accounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reconfirmationUrl, forKey: .reconfirmationUrl)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(urlValidFrom, forKey: .urlValidFrom)
        try container.encodeIfPresent(urlValidTo, forKey: .urlValidTo)
        try container.encodeIfPresent(redirect, forKey: .redirect)
        try container.encodeIfPresent(lastAccessed, forKey: .lastAccessed)
        try container.encodeIfPresent(lastSubmitted, forKey: .lastSubmitted)
        try container.encodeIfPresent(accounts, forKey: .accounts)
    }
}

