//
// Requisition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** RequisitionSerializer. */
public struct Requisition: Sendable, Codable, Hashable {

    public static let redirectRule = StringRule(minLength: nil, maxLength: 1024, pattern: nil)
    public static let referenceRule = StringRule(minLength: nil, maxLength: 256, pattern: nil)
    public static let userLanguageRule = StringRule(minLength: nil, maxLength: 5, pattern: nil)
    public static let ssnRule = StringRule(minLength: nil, maxLength: 64, pattern: nil)
    public var id: UUID?
    /** The date & time at which the requisition was created. */
    public var created: Date?
    /** redirect URL to your application after end-user authorization with ASPSP */
    public var redirect: String?
    /** status of this requisition */
    public var status: StatusEnum?
    /** an Institution ID for this Requisition */
    public var institutionId: String
    /** EUA associated with this requisition */
    public var agreement: UUID?
    /** additional ID to identify the end user */
    public var reference: String?
    /** array of account IDs retrieved within a scope of this requisition */
    public var accounts: [UUID]?
    /** A two-letter country code (ISO 639-1) */
    public var userLanguage: String?
    /** link to initiate authorization with Institution */
    public var link: String? = "https://ob.gocardless.com/psd2/start/3fa85f64-5717-4562-b3fc-2c963f66afa6/SANDBOXFINANCE_SFIN0000"
    /** optional SSN field to verify ownership of the account */
    public var ssn: String?
    /** option to enable account selection view for the end user */
    public var accountSelection: Bool? = false
    /** enable redirect back to the client after account list received */
    public var redirectImmediate: Bool? = false

    public init(id: UUID? = nil, created: Date? = nil, redirect: String?, status: StatusEnum? = nil, institutionId: String, agreement: UUID? = nil, reference: String? = nil, accounts: [UUID]? = nil, userLanguage: String? = nil, link: String? = "https://ob.gocardless.com/psd2/start/3fa85f64-5717-4562-b3fc-2c963f66afa6/SANDBOXFINANCE_SFIN0000", ssn: String? = nil, accountSelection: Bool? = false, redirectImmediate: Bool? = false) {
        self.id = id
        self.created = created
        self.redirect = redirect
        self.status = status
        self.institutionId = institutionId
        self.agreement = agreement
        self.reference = reference
        self.accounts = accounts
        self.userLanguage = userLanguage
        self.link = link
        self.ssn = ssn
        self.accountSelection = accountSelection
        self.redirectImmediate = redirectImmediate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case created
        case redirect
        case status
        case institutionId = "institution_id"
        case agreement
        case reference
        case accounts
        case userLanguage = "user_language"
        case link
        case ssn
        case accountSelection = "account_selection"
        case redirectImmediate = "redirect_immediate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encode(redirect, forKey: .redirect)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(institutionId, forKey: .institutionId)
        try container.encodeIfPresent(agreement, forKey: .agreement)
        try container.encodeIfPresent(reference, forKey: .reference)
        try container.encodeIfPresent(accounts, forKey: .accounts)
        try container.encodeIfPresent(userLanguage, forKey: .userLanguage)
        try container.encodeIfPresent(link, forKey: .link)
        try container.encodeIfPresent(ssn, forKey: .ssn)
        try container.encodeIfPresent(accountSelection, forKey: .accountSelection)
        try container.encodeIfPresent(redirectImmediate, forKey: .redirectImmediate)
    }
}


extension Requisition: Identifiable {}
