//
// SpectacularJWTRefresh.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** Refresh Access token. */
public struct SpectacularJWTRefresh: Sendable, Content, Hashable {

    /** Your access token */
    public var access: String?
    /** Access token expires in seconds */
    public var accessExpires: Int? = 86400

    public init(access: String? = nil, accessExpires: Int? = 86400) {
        self.access = access
        self.accessExpires = accessExpires
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case access
        case accessExpires = "access_expires"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(access, forKey: .access)
        try container.encodeIfPresent(accessExpires, forKey: .accessExpires)
    }
}

