//
// SpectacularJWTObtain.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

/** Obtain new JWT pair. */
public struct SpectacularJWTObtain: Sendable, Content, Hashable {

    /** Your access token */
    public var access: String?
    /** Access token expires in seconds */
    public var accessExpires: Int? = 86400
    /** Your refresh token */
    public var refresh: String?
    /** Refresh token expires in seconds */
    public var refreshExpires: Int? = 2592000

    public init(access: String? = nil, accessExpires: Int? = 86400, refresh: String? = nil, refreshExpires: Int? = 2592000) {
        self.access = access
        self.accessExpires = accessExpires
        self.refresh = refresh
        self.refreshExpires = refreshExpires
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case access
        case accessExpires = "access_expires"
        case refresh
        case refreshExpires = "refresh_expires"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(access, forKey: .access)
        try container.encodeIfPresent(accessExpires, forKey: .accessExpires)
        try container.encodeIfPresent(refresh, forKey: .refresh)
        try container.encodeIfPresent(refreshExpires, forKey: .refreshExpires)
    }
}

