//
// StatusEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

public enum StatusEnum: String, Sendable, Content, Hashable, CaseIterable {
    case cr = "CR"
    case id = "ID"
    case ln = "LN"
    case rj = "RJ"
    case er = "ER"
    case su = "SU"
    case ex = "EX"
    case gc = "GC"
    case ua = "UA"
    case ga = "GA"
    case sa = "SA"
}
