//
// SuccessfulDeleteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SuccessfulDeleteResponse: Sendable, Codable, Hashable {

    public var summary: String
    public var detail: String

    public init(summary: String, detail: String) {
        self.summary = summary
        self.detail = detail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case summary
        case detail
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(summary, forKey: .summary)
        try container.encode(detail, forKey: .detail)
    }
}

