# Generated by Django 3.2.10 on 2022-05-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20190210_1703'),
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('bar', 'Bar'), ('pie', 'Pie'), ('line', 'Line')], max_length=10)),
                ('date_range', models.CharField(max_length=255)),
                ('tag_filter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('day', 'day'), ('month', 'month'), ('tags', 'tags'), ('sign', 'sign')], max_length=10)),
                ('hide_others', models.BooleanField(blank=True, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.graphv2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorizontalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('day', 'day'), ('month', 'month'), ('tags', 'tags'), ('sign', 'sign')], max_length=10)),
                ('hide_others', models.BooleanField(blank=True, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.graphv2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorizontalGroupTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.horizontalgroup')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.tag')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.group')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.tag')),
            ],
        ),
    ]
