# Generated by Django 3.2.15 on 2023-02-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_graphv2_group_grouptags_horizontalgroup_horizontalgrouptags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouptags',
            options={'ordering': ('group', 'position')},
        ),
        migrations.AlterModelOptions(
            name='horizontalgrouptags',
            options={'ordering': ('group', 'position')},
        ),
        migrations.AddField(
            model_name='grouptags',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='horizontalgrouptags',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
