# Generated by Django 3.2.10 on 2022-05-26 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_graphv2_group_grouptags_horizontalgroup_horizontalgrouptags'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphv2',
            name='old_graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graphs.graph'),
        ),
    ]
