# Generated by Django 3.2.10 on 2022-06-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20190210_1703'),
        ('graphs', '0003_graphv2_old_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphv2',
            name='accumulate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graphv2',
            name='tag_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.tag'),
        ),
        migrations.AlterField(
            model_name='group',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='graphs.graphv2'),
        ),
        migrations.AlterField(
            model_name='grouptags',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tags', to='graphs.group'),
        ),
        migrations.AlterField(
            model_name='horizontalgroup',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horizontal_group', to='graphs.graphv2'),
        ),
        migrations.AlterField(
            model_name='horizontalgrouptags',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tags', to='graphs.horizontalgroup'),
        ),
    ]
