# Generated by Django 3.2.10 on 2022-09-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20220616_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='graph',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='graphs.graphv2'),
        ),
        migrations.AlterField(
            model_name='horizontalgroup',
            name='graph',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horizontal_group', to='graphs.graphv2'),
        ),
    ]
