# Generated by Django 2.0.8 on 2018-11-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0004_auto_20181123_0718'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='RawDataSource',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('movement_name', models.CharField(max_length=255)),
                        ('date', models.DateField()),
                        ('date_value', models.DateField(null=True)),
                        ('details', models.TextField(blank=True, null=True)),
                        ('value', models.FloatField()),
                        ('kind', models.CharField(max_length=255)),
                    ],
                    options={
                        'ordering': ('-date', '-date_value', 'movement_name'),
                        'indexes': [models.Index(fields=['kind', 'movement_name', 'date', 'value'], name='core_rawdat_kind_b0d86a_idx')],
                    },
                ),
            ],
        ),
    ]
