# Generated by Django 2.0.10 on 2019-01-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasource',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
