# Generated by Django 2.0.10 on 2019-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rawdatasource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatasource',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
