# Generated by Django 3.2.10 on 2021-12-21 16:46

from django.db import migrations, models


def initialize_page_key(apps, schema_editor):
    Rds = apps.get_model('core', 'RawDataSource')
    for rds in Rds.objects.all():
        rds.page_key = f"{rds.date};{rds.pk}"
        rds.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190210_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdatasource',
            name='page_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='rawdatasource',
            index=models.Index(fields=['page_key'], name='core_rawdat_page_ke_489283_idx'),
        ),
        migrations.RunPython(initialize_page_key, reverse_code=lambda x,y: x)
    ]
