overwrite: true
schema: "http://localhost:8080/graphql"
documents: "src/view/**/*.graphql"
generates:
  src/view/api/graphql/generated.ts:
    plugins:
      - typescript
      - typescript-urql
      - typescript-operations
    config:
      withComponent: false
      withHooks: true
      typesPrefix: GQL
      nonOptionalTypename: false
      scalars:
        Date: Date
        DateOnly: string
        UUID: string
