# Generated by Django 2.0.1 on 2018-03-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawdatasource',
            options={'ordering': ('-date', '-date_value')},
        ),
    ]
