# Generated by Django 2.0.1 on 2018-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_auto_20180329_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatasource',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statusreportrow',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
