//
// AgreementsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AgreementsAPI {

    /**

     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter enduserAcceptanceDetailsRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: EndUserAgreement
     */
    open class func acceptEUA(id: UUID, enduserAcceptanceDetailsRequest: EnduserAcceptanceDetailsRequest, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> EndUserAgreement {
        return try await acceptEUAWithRequestBuilder(id: id, enduserAcceptanceDetailsRequest: enduserAcceptanceDetailsRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - PUT /api/v2/agreements/enduser/{id}/accept/
     - Accept an end-user agreement via the API
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter enduserAcceptanceDetailsRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<EndUserAgreement> 
     */
    open class func acceptEUAWithRequestBuilder(id: UUID, enduserAcceptanceDetailsRequest: EnduserAcceptanceDetailsRequest, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<EndUserAgreement> {
        var localVariablePath = "/api/v2/agreements/enduser/{id}/accept/"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: enduserAcceptanceDetailsRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EndUserAgreement>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter endUserAgreementRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: EndUserAgreement
     */
    open class func createEUA(endUserAgreementRequest: EndUserAgreementRequest, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> EndUserAgreement {
        return try await createEUAWithRequestBuilder(endUserAgreementRequest: endUserAgreementRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v2/agreements/enduser/
     - API endpoints related to end-user agreements.
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter endUserAgreementRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<EndUserAgreement> 
     */
    open class func createEUAWithRequestBuilder(endUserAgreementRequest: EndUserAgreementRequest, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<EndUserAgreement> {
        let localVariablePath = "/api/v2/agreements/enduser/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: endUserAgreementRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EndUserAgreement>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter reconfirmationRetrieveRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ReconfirmationRetrieve
     */
    open class func createEUAReconfirmation(id: UUID, reconfirmationRetrieveRequest: ReconfirmationRetrieveRequest? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> ReconfirmationRetrieve {
        return try await createEUAReconfirmationWithRequestBuilder(id: id, reconfirmationRetrieveRequest: reconfirmationRetrieveRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v2/agreements/enduser/{id}/reconfirm/
     - Create EUA reconfirmation
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter reconfirmationRetrieveRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ReconfirmationRetrieve> 
     */
    open class func createEUAReconfirmationWithRequestBuilder(id: UUID, reconfirmationRetrieveRequest: ReconfirmationRetrieveRequest? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<ReconfirmationRetrieve> {
        var localVariablePath = "/api/v2/agreements/enduser/{id}/reconfirm/"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: reconfirmationRetrieveRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReconfirmationRetrieve>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SuccessfulDeleteResponse
     */
    open class func deleteEUAById(id: UUID, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> SuccessfulDeleteResponse {
        return try await deleteEUAByIdWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /api/v2/agreements/enduser/{id}/
     - Delete an end user agreement
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SuccessfulDeleteResponse> 
     */
    open class func deleteEUAByIdWithRequestBuilder(id: UUID, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<SuccessfulDeleteResponse> {
        var localVariablePath = "/api/v2/agreements/enduser/{id}/"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessfulDeleteResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter limit: (query) Number of results to return per page. (optional, default to 100)
     - parameter offset: (query) The initial zero-based index from which to return the results. (optional, default to 0)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PaginatedEndUserAgreementList
     */
    open class func retrieveAllAgreements(limit: Int? = nil, offset: Int? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> PaginatedEndUserAgreementList {
        return try await retrieveAllAgreementsWithRequestBuilder(limit: limit, offset: offset, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v2/agreements/enduser/
     - Retrieve all End User Agreements belonging to the company
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter limit: (query) Number of results to return per page. (optional, default to 100)
     - parameter offset: (query) The initial zero-based index from which to return the results. (optional, default to 0)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PaginatedEndUserAgreementList> 
     */
    open class func retrieveAllAgreementsWithRequestBuilder(limit: Int? = nil, offset: Int? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<PaginatedEndUserAgreementList> {
        let localVariablePath = "/api/v2/agreements/enduser/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedEndUserAgreementList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: EndUserAgreement
     */
    open class func retrieveEUAById(id: UUID, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> EndUserAgreement {
        return try await retrieveEUAByIdWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v2/agreements/enduser/{id}/
     - Retrieve end user agreement by ID
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<EndUserAgreement> 
     */
    open class func retrieveEUAByIdWithRequestBuilder(id: UUID, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<EndUserAgreement> {
        var localVariablePath = "/api/v2/agreements/enduser/{id}/"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EndUserAgreement>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ReconfirmationRetrieve
     */
    open class func retrieveEUAReconfirmation(id: UUID, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> ReconfirmationRetrieve {
        return try await retrieveEUAReconfirmationWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v2/agreements/enduser/{id}/reconfirm/
     - Retrieve EUA reconfirmation
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ReconfirmationRetrieve> 
     */
    open class func retrieveEUAReconfirmationWithRequestBuilder(id: UUID, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<ReconfirmationRetrieve> {
        var localVariablePath = "/api/v2/agreements/enduser/{id}/reconfirm/"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ReconfirmationRetrieve>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
