//
// AgreementsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

open class AgreementsAPI {

    /**
     PUT /api/v2/agreements/enduser/{id}/accept/
     Accept an end-user agreement via the API
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter enduserAcceptanceDetailsRequest: (body)  
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func acceptEUARaw(id: UUID, enduserAcceptanceDetailsRequest: EnduserAcceptanceDetailsRequest, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var localVariablePath = "/api/v2/agreements/enduser/{id}/accept/"
        let idPreEscape = String(describing: id)
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.PUT, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            
            try localVariableRequest.content.encode(enduserAcceptanceDetailsRequest, using: apiConfiguration.contentConfiguration.requireEncoder(for: EnduserAcceptanceDetailsRequest.defaultContentType))
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum AcceptEUA {
        case http200(value: EndUserAgreement, raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http405(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     PUT /api/v2/agreements/enduser/{id}/accept/
     Accept an end-user agreement via the API
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter enduserAcceptanceDetailsRequest: (body)  
     - returns: `EventLoopFuture` of `AcceptEUA` 
     */
    open class func acceptEUA(id: UUID, enduserAcceptanceDetailsRequest: EnduserAcceptanceDetailsRequest, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<AcceptEUA> {
        return acceptEUARaw(id: id, enduserAcceptanceDetailsRequest: enduserAcceptanceDetailsRequest, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> AcceptEUA in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(EndUserAgreement.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: EndUserAgreement.defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 405:
                return .http405(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }

    /**
     POST /api/v2/agreements/enduser/
     API endpoints related to end-user agreements.
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter endUserAgreementRequest: (body)  
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func createEUARaw(endUserAgreementRequest: EndUserAgreementRequest, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        let localVariablePath = "/api/v2/agreements/enduser/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.POST, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            
            try localVariableRequest.content.encode(endUserAgreementRequest, using: apiConfiguration.contentConfiguration.requireEncoder(for: EndUserAgreementRequest.defaultContentType))
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum CreateEUA {
        case http201(value: EndUserAgreement, raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http402(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     POST /api/v2/agreements/enduser/
     API endpoints related to end-user agreements.
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter endUserAgreementRequest: (body)  
     - returns: `EventLoopFuture` of `CreateEUA` 
     */
    open class func createEUA(endUserAgreementRequest: EndUserAgreementRequest, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<CreateEUA> {
        return createEUARaw(endUserAgreementRequest: endUserAgreementRequest, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> CreateEUA in
            switch response.status.code {
            case 201:
                return .http201(value: try response.content.decode(EndUserAgreement.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: EndUserAgreement.defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 402:
                return .http402(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }

    /**
     POST /api/v2/agreements/enduser/{id}/reconfirm/
     Create EUA reconfirmation
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter reconfirmationRetrieveRequest: (body)  (optional)
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func createEUAReconfirmationRaw(id: UUID, reconfirmationRetrieveRequest: ReconfirmationRetrieveRequest? = nil, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var localVariablePath = "/api/v2/agreements/enduser/{id}/reconfirm/"
        let idPreEscape = String(describing: id)
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.POST, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            
            if let localVariableBody = reconfirmationRetrieveRequest {
                try localVariableRequest.content.encode(localVariableBody, using: apiConfiguration.contentConfiguration.requireEncoder(for: ReconfirmationRetrieveRequest.defaultContentType))
            }
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum CreateEUAReconfirmation {
        case http201(value: ReconfirmationRetrieve, raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     POST /api/v2/agreements/enduser/{id}/reconfirm/
     Create EUA reconfirmation
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - parameter reconfirmationRetrieveRequest: (body)  (optional)
     - returns: `EventLoopFuture` of `CreateEUAReconfirmation` 
     */
    open class func createEUAReconfirmation(id: UUID, reconfirmationRetrieveRequest: ReconfirmationRetrieveRequest? = nil, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<CreateEUAReconfirmation> {
        return createEUAReconfirmationRaw(id: id, reconfirmationRetrieveRequest: reconfirmationRetrieveRequest, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> CreateEUAReconfirmation in
            switch response.status.code {
            case 201:
                return .http201(value: try response.content.decode(ReconfirmationRetrieve.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ReconfirmationRetrieve.defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }

    /**
     DELETE /api/v2/agreements/enduser/{id}/
     Delete an end user agreement
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func deleteEUAByIdRaw(id: UUID, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var localVariablePath = "/api/v2/agreements/enduser/{id}/"
        let idPreEscape = String(describing: id)
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.DELETE, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum DeleteEUAById {
        case http200(value: SuccessfulDeleteResponse, raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     DELETE /api/v2/agreements/enduser/{id}/
     Delete an end user agreement
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - returns: `EventLoopFuture` of `DeleteEUAById` 
     */
    open class func deleteEUAById(id: UUID, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<DeleteEUAById> {
        return deleteEUAByIdRaw(id: id, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> DeleteEUAById in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(SuccessfulDeleteResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: SuccessfulDeleteResponse.defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }

    /**
     GET /api/v2/agreements/enduser/
     Retrieve all End User Agreements belonging to the company
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter limit: (query) Number of results to return per page. (optional, default to 100)
     - parameter offset: (query) The initial zero-based index from which to return the results. (optional, default to 0)
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func retrieveAllAgreementsRaw(limit: Int? = nil, offset: Int? = nil, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        let localVariablePath = "/api/v2/agreements/enduser/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.GET, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            struct QueryParams: Content {
                var limit: Int?
                var offset: Int?

                enum CodingKeys: String, CodingKey {
                    case limit = "limit"
                    case offset = "offset"
                }
            }
            try localVariableRequest.query.encode(QueryParams(limit: limit, offset: offset))
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum RetrieveAllAgreements {
        case http200(value: PaginatedEndUserAgreementList, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     GET /api/v2/agreements/enduser/
     Retrieve all End User Agreements belonging to the company
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter limit: (query) Number of results to return per page. (optional, default to 100)
     - parameter offset: (query) The initial zero-based index from which to return the results. (optional, default to 0)
     - returns: `EventLoopFuture` of `RetrieveAllAgreements` 
     */
    open class func retrieveAllAgreements(limit: Int? = nil, offset: Int? = nil, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<RetrieveAllAgreements> {
        return retrieveAllAgreementsRaw(limit: limit, offset: offset, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> RetrieveAllAgreements in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(PaginatedEndUserAgreementList.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: PaginatedEndUserAgreementList.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }

    /**
     GET /api/v2/agreements/enduser/{id}/
     Retrieve end user agreement by ID
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func retrieveEUAByIdRaw(id: UUID, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var localVariablePath = "/api/v2/agreements/enduser/{id}/"
        let idPreEscape = String(describing: id)
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.GET, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum RetrieveEUAById {
        case http200(value: EndUserAgreement, raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     GET /api/v2/agreements/enduser/{id}/
     Retrieve end user agreement by ID
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - returns: `EventLoopFuture` of `RetrieveEUAById` 
     */
    open class func retrieveEUAById(id: UUID, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<RetrieveEUAById> {
        return retrieveEUAByIdRaw(id: id, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> RetrieveEUAById in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(EndUserAgreement.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: EndUserAgreement.defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }

    /**
     GET /api/v2/agreements/enduser/{id}/reconfirm/
     Retrieve EUA reconfirmation
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func retrieveEUAReconfirmationRaw(id: UUID, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var localVariablePath = "/api/v2/agreements/enduser/{id}/reconfirm/"
        let idPreEscape = String(describing: id)
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.GET, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum RetrieveEUAReconfirmation {
        case http200(value: ReconfirmationRetrieve, raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     GET /api/v2/agreements/enduser/{id}/reconfirm/
     Retrieve EUA reconfirmation
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this end user agreement. 
     - returns: `EventLoopFuture` of `RetrieveEUAReconfirmation` 
     */
    open class func retrieveEUAReconfirmation(id: UUID, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<RetrieveEUAReconfirmation> {
        return retrieveEUAReconfirmationRaw(id: id, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> RetrieveEUAReconfirmation in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(ReconfirmationRetrieve.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ReconfirmationRetrieve.defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }
}
