//
// InstitutionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

open class InstitutionsAPI {

    /**
     GET /api/v2/institutions/
     List all available institutions
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter accessScopesSupported: (query) Boolean value, indicating if access scopes are supported (optional)
     - parameter accountSelectionSupported: (query) Boolean value, indicating if account selection is supported (optional)
     - parameter businessAccountsSupported: (query) Boolean value, indicating if business accounts are supported (optional)
     - parameter cardAccountsSupported: (query) Boolean value, indicating if card accounts are supported (optional)
     - parameter corporateAccountsSupported: (query) Boolean value, indicating if corporate accounts are supported (optional)
     - parameter country: (query) ISO 3166 two-character country code (optional)
     - parameter pendingTransactionsSupported: (query) Boolean value, indicating if pending transactions are supported (optional)
     - parameter privateAccountsSupported: (query) Boolean value, indicating if private accounts are supported (optional)
     - parameter readDebtorAccountSupported: (query) Boolean value, indicating if debtor account can be read before submitting payment (optional)
     - parameter readRefundAccountSupported: (query) Boolean value, indicating if read refund account is supported (optional)
     - parameter separateContinuousHistoryConsentSupported: (query) Boolean value, indicating if separate consent for continuous history is supported (optional)
     - parameter ssnVerificationSupported: (query) Boolean value, indicating if ssn verification is supported (optional)
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func retrieveAllSupportedInstitutionsInAGivenCountryRaw(accessScopesSupported: String? = nil, accountSelectionSupported: String? = nil, businessAccountsSupported: String? = nil, cardAccountsSupported: String? = nil, corporateAccountsSupported: String? = nil, country: String? = nil, pendingTransactionsSupported: String? = nil, privateAccountsSupported: String? = nil, readDebtorAccountSupported: String? = nil, readRefundAccountSupported: String? = nil, separateContinuousHistoryConsentSupported: String? = nil, ssnVerificationSupported: String? = nil, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        let localVariablePath = "/api/v2/institutions/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.GET, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            struct QueryParams: Content {
                var accessScopesSupported: String?
                var accountSelectionSupported: String?
                var businessAccountsSupported: String?
                var cardAccountsSupported: String?
                var corporateAccountsSupported: String?
                var country: String?
                var pendingTransactionsSupported: String?
                var privateAccountsSupported: String?
                var readDebtorAccountSupported: String?
                var readRefundAccountSupported: String?
                var separateContinuousHistoryConsentSupported: String?
                var ssnVerificationSupported: String?

                enum CodingKeys: String, CodingKey {
                    case accessScopesSupported = "access_scopes_supported"
                    case accountSelectionSupported = "account_selection_supported"
                    case businessAccountsSupported = "business_accounts_supported"
                    case cardAccountsSupported = "card_accounts_supported"
                    case corporateAccountsSupported = "corporate_accounts_supported"
                    case country = "country"
                    case pendingTransactionsSupported = "pending_transactions_supported"
                    case privateAccountsSupported = "private_accounts_supported"
                    case readDebtorAccountSupported = "read_debtor_account_supported"
                    case readRefundAccountSupported = "read_refund_account_supported"
                    case separateContinuousHistoryConsentSupported = "separate_continuous_history_consent_supported"
                    case ssnVerificationSupported = "ssn_verification_supported"
                }
            }
            try localVariableRequest.query.encode(QueryParams(accessScopesSupported: accessScopesSupported, accountSelectionSupported: accountSelectionSupported, businessAccountsSupported: businessAccountsSupported, cardAccountsSupported: cardAccountsSupported, corporateAccountsSupported: corporateAccountsSupported, country: country, pendingTransactionsSupported: pendingTransactionsSupported, privateAccountsSupported: privateAccountsSupported, readDebtorAccountSupported: readDebtorAccountSupported, readRefundAccountSupported: readRefundAccountSupported, separateContinuousHistoryConsentSupported: separateContinuousHistoryConsentSupported, ssnVerificationSupported: ssnVerificationSupported))
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum RetrieveAllSupportedInstitutionsInAGivenCountry {
        case http200(value: [Integration], raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     GET /api/v2/institutions/
     List all available institutions
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter accessScopesSupported: (query) Boolean value, indicating if access scopes are supported (optional)
     - parameter accountSelectionSupported: (query) Boolean value, indicating if account selection is supported (optional)
     - parameter businessAccountsSupported: (query) Boolean value, indicating if business accounts are supported (optional)
     - parameter cardAccountsSupported: (query) Boolean value, indicating if card accounts are supported (optional)
     - parameter corporateAccountsSupported: (query) Boolean value, indicating if corporate accounts are supported (optional)
     - parameter country: (query) ISO 3166 two-character country code (optional)
     - parameter pendingTransactionsSupported: (query) Boolean value, indicating if pending transactions are supported (optional)
     - parameter privateAccountsSupported: (query) Boolean value, indicating if private accounts are supported (optional)
     - parameter readDebtorAccountSupported: (query) Boolean value, indicating if debtor account can be read before submitting payment (optional)
     - parameter readRefundAccountSupported: (query) Boolean value, indicating if read refund account is supported (optional)
     - parameter separateContinuousHistoryConsentSupported: (query) Boolean value, indicating if separate consent for continuous history is supported (optional)
     - parameter ssnVerificationSupported: (query) Boolean value, indicating if ssn verification is supported (optional)
     - returns: `EventLoopFuture` of `RetrieveAllSupportedInstitutionsInAGivenCountry` 
     */
    open class func retrieveAllSupportedInstitutionsInAGivenCountry(accessScopesSupported: String? = nil, accountSelectionSupported: String? = nil, businessAccountsSupported: String? = nil, cardAccountsSupported: String? = nil, corporateAccountsSupported: String? = nil, country: String? = nil, pendingTransactionsSupported: String? = nil, privateAccountsSupported: String? = nil, readDebtorAccountSupported: String? = nil, readRefundAccountSupported: String? = nil, separateContinuousHistoryConsentSupported: String? = nil, ssnVerificationSupported: String? = nil, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<RetrieveAllSupportedInstitutionsInAGivenCountry> {
        return retrieveAllSupportedInstitutionsInAGivenCountryRaw(accessScopesSupported: accessScopesSupported, accountSelectionSupported: accountSelectionSupported, businessAccountsSupported: businessAccountsSupported, cardAccountsSupported: cardAccountsSupported, corporateAccountsSupported: corporateAccountsSupported, country: country, pendingTransactionsSupported: pendingTransactionsSupported, privateAccountsSupported: privateAccountsSupported, readDebtorAccountSupported: readDebtorAccountSupported, readRefundAccountSupported: readRefundAccountSupported, separateContinuousHistoryConsentSupported: separateContinuousHistoryConsentSupported, ssnVerificationSupported: ssnVerificationSupported, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> RetrieveAllSupportedInstitutionsInAGivenCountry in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode([Integration].self, using: apiConfiguration.contentConfiguration.requireDecoder(for: [Integration].defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }

    /**
     GET /api/v2/institutions/{id}/
     Get details about a specific Institution and its supported features
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path)  
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func retrieveInstitutionRaw(id: String, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var localVariablePath = "/api/v2/institutions/{id}/"
        let idPreEscape = String(describing: id)
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.GET, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum RetrieveInstitution {
        case http200(value: IntegrationRetrieve, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     GET /api/v2/institutions/{id}/
     Get details about a specific Institution and its supported features
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path)  
     - returns: `EventLoopFuture` of `RetrieveInstitution` 
     */
    open class func retrieveInstitution(id: String, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<RetrieveInstitution> {
        return retrieveInstitutionRaw(id: id, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> RetrieveInstitution in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(IntegrationRetrieve.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: IntegrationRetrieve.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }
}
