//
// InstitutionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class InstitutionsAPI {

    /**

     - parameter accessScopesSupported: (query) Boolean value, indicating if access scopes are supported (optional)
     - parameter accountSelectionSupported: (query) Boolean value, indicating if account selection is supported (optional)
     - parameter businessAccountsSupported: (query) Boolean value, indicating if business accounts are supported (optional)
     - parameter cardAccountsSupported: (query) Boolean value, indicating if card accounts are supported (optional)
     - parameter corporateAccountsSupported: (query) Boolean value, indicating if corporate accounts are supported (optional)
     - parameter country: (query) ISO 3166 two-character country code (optional)
     - parameter pendingTransactionsSupported: (query) Boolean value, indicating if pending transactions are supported (optional)
     - parameter privateAccountsSupported: (query) Boolean value, indicating if private accounts are supported (optional)
     - parameter readDebtorAccountSupported: (query) Boolean value, indicating if debtor account can be read before submitting payment (optional)
     - parameter readRefundAccountSupported: (query) Boolean value, indicating if read refund account is supported (optional)
     - parameter separateContinuousHistoryConsentSupported: (query) Boolean value, indicating if separate consent for continuous history is supported (optional)
     - parameter ssnVerificationSupported: (query) Boolean value, indicating if ssn verification is supported (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [Integration]
     */
    open class func retrieveAllSupportedInstitutionsInAGivenCountry(accessScopesSupported: String? = nil, accountSelectionSupported: String? = nil, businessAccountsSupported: String? = nil, cardAccountsSupported: String? = nil, corporateAccountsSupported: String? = nil, country: String? = nil, pendingTransactionsSupported: String? = nil, privateAccountsSupported: String? = nil, readDebtorAccountSupported: String? = nil, readRefundAccountSupported: String? = nil, separateContinuousHistoryConsentSupported: String? = nil, ssnVerificationSupported: String? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> [Integration] {
        return try await retrieveAllSupportedInstitutionsInAGivenCountryWithRequestBuilder(accessScopesSupported: accessScopesSupported, accountSelectionSupported: accountSelectionSupported, businessAccountsSupported: businessAccountsSupported, cardAccountsSupported: cardAccountsSupported, corporateAccountsSupported: corporateAccountsSupported, country: country, pendingTransactionsSupported: pendingTransactionsSupported, privateAccountsSupported: privateAccountsSupported, readDebtorAccountSupported: readDebtorAccountSupported, readRefundAccountSupported: readRefundAccountSupported, separateContinuousHistoryConsentSupported: separateContinuousHistoryConsentSupported, ssnVerificationSupported: ssnVerificationSupported, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v2/institutions/
     - List all available institutions
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter accessScopesSupported: (query) Boolean value, indicating if access scopes are supported (optional)
     - parameter accountSelectionSupported: (query) Boolean value, indicating if account selection is supported (optional)
     - parameter businessAccountsSupported: (query) Boolean value, indicating if business accounts are supported (optional)
     - parameter cardAccountsSupported: (query) Boolean value, indicating if card accounts are supported (optional)
     - parameter corporateAccountsSupported: (query) Boolean value, indicating if corporate accounts are supported (optional)
     - parameter country: (query) ISO 3166 two-character country code (optional)
     - parameter pendingTransactionsSupported: (query) Boolean value, indicating if pending transactions are supported (optional)
     - parameter privateAccountsSupported: (query) Boolean value, indicating if private accounts are supported (optional)
     - parameter readDebtorAccountSupported: (query) Boolean value, indicating if debtor account can be read before submitting payment (optional)
     - parameter readRefundAccountSupported: (query) Boolean value, indicating if read refund account is supported (optional)
     - parameter separateContinuousHistoryConsentSupported: (query) Boolean value, indicating if separate consent for continuous history is supported (optional)
     - parameter ssnVerificationSupported: (query) Boolean value, indicating if ssn verification is supported (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[Integration]> 
     */
    open class func retrieveAllSupportedInstitutionsInAGivenCountryWithRequestBuilder(accessScopesSupported: String? = nil, accountSelectionSupported: String? = nil, businessAccountsSupported: String? = nil, cardAccountsSupported: String? = nil, corporateAccountsSupported: String? = nil, country: String? = nil, pendingTransactionsSupported: String? = nil, privateAccountsSupported: String? = nil, readDebtorAccountSupported: String? = nil, readRefundAccountSupported: String? = nil, separateContinuousHistoryConsentSupported: String? = nil, ssnVerificationSupported: String? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<[Integration]> {
        let localVariablePath = "/api/v2/institutions/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "access_scopes_supported": (wrappedValue: accessScopesSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "account_selection_supported": (wrappedValue: accountSelectionSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "business_accounts_supported": (wrappedValue: businessAccountsSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "card_accounts_supported": (wrappedValue: cardAccountsSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "corporate_accounts_supported": (wrappedValue: corporateAccountsSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "country": (wrappedValue: country?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pending_transactions_supported": (wrappedValue: pendingTransactionsSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "private_accounts_supported": (wrappedValue: privateAccountsSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "read_debtor_account_supported": (wrappedValue: readDebtorAccountSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "read_refund_account_supported": (wrappedValue: readRefundAccountSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "separate_continuous_history_consent_supported": (wrappedValue: separateContinuousHistoryConsentSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "ssn_verification_supported": (wrappedValue: ssnVerificationSupported?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Integration]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: IntegrationRetrieve
     */
    open class func retrieveInstitution(id: String, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> IntegrationRetrieve {
        return try await retrieveInstitutionWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v2/institutions/{id}/
     - Get details about a specific Institution and its supported features
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<IntegrationRetrieve> 
     */
    open class func retrieveInstitutionWithRequestBuilder(id: String, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<IntegrationRetrieve> {
        var localVariablePath = "/api/v2/institutions/{id}/"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IntegrationRetrieve>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
