//
// RequisitionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor

open class RequisitionsAPI {

    /**
     POST /api/v2/requisitions/
     Create a new requisition
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter requisitionRequest: (body)  
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func createRequisitionRaw(requisitionRequest: RequisitionRequest, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        let localVariablePath = "/api/v2/requisitions/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.POST, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            
            try localVariableRequest.content.encode(requisitionRequest, using: apiConfiguration.contentConfiguration.requireEncoder(for: RequisitionRequest.defaultContentType))
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum CreateRequisition {
        case http201(value: SpectacularRequisition, raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http402(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     POST /api/v2/requisitions/
     Create a new requisition
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter requisitionRequest: (body)  
     - returns: `EventLoopFuture` of `CreateRequisition` 
     */
    open class func createRequisition(requisitionRequest: RequisitionRequest, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<CreateRequisition> {
        return createRequisitionRaw(requisitionRequest: requisitionRequest, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> CreateRequisition in
            switch response.status.code {
            case 201:
                return .http201(value: try response.content.decode(SpectacularRequisition.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: SpectacularRequisition.defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 402:
                return .http402(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }

    /**
     DELETE /api/v2/requisitions/{id}/
     Delete requisition and its end user agreement
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this requisition. 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func deleteRequisitionByIdRaw(id: UUID, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var localVariablePath = "/api/v2/requisitions/{id}/"
        let idPreEscape = String(describing: id)
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.DELETE, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum DeleteRequisitionById {
        case http200(value: SuccessfulDeleteResponse, raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     DELETE /api/v2/requisitions/{id}/
     Delete requisition and its end user agreement
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this requisition. 
     - returns: `EventLoopFuture` of `DeleteRequisitionById` 
     */
    open class func deleteRequisitionById(id: UUID, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<DeleteRequisitionById> {
        return deleteRequisitionByIdRaw(id: id, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> DeleteRequisitionById in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(SuccessfulDeleteResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: SuccessfulDeleteResponse.defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }

    /**
     GET /api/v2/requisitions/{id}/
     Retrieve a requisition by ID
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this requisition. 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func requisitionByIdRaw(id: UUID, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var localVariablePath = "/api/v2/requisitions/{id}/"
        let idPreEscape = String(describing: id)
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.GET, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum RequisitionById {
        case http200(value: Requisition, raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     GET /api/v2/requisitions/{id}/
     Retrieve a requisition by ID
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this requisition. 
     - returns: `EventLoopFuture` of `RequisitionById` 
     */
    open class func requisitionById(id: UUID, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<RequisitionById> {
        return requisitionByIdRaw(id: id, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> RequisitionById in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(Requisition.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: Requisition.defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }

    /**
     GET /api/v2/requisitions/
     Retrieve all requisitions belonging to the company
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter limit: (query) Number of results to return per page. (optional, default to 100)
     - parameter offset: (query) The initial zero-based index from which to return the results. (optional, default to 0)
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    open class func retrieveAllRequisitionsRaw(limit: Int? = nil, offset: Int? = nil, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        let localVariablePath = "/api/v2/requisitions/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath

        guard let localVariableApiClient = apiConfiguration.apiClient else {
            fatalError("apiConfiguration.apiClient is not set.")
        }

        return localVariableApiClient.send(.GET, headers: headers ?? apiConfiguration.customHeaders, to: URI(string: localVariableURLString)) { localVariableRequest in
            try apiConfiguration.apiWrapper(&localVariableRequest)
            
            struct QueryParams: Content {
                var limit: Int?
                var offset: Int?

                enum CodingKeys: String, CodingKey {
                    case limit = "limit"
                    case offset = "offset"
                }
            }
            try localVariableRequest.query.encode(QueryParams(limit: limit, offset: offset))
            
            try beforeSend(&localVariableRequest)
        }
    }

    public enum RetrieveAllRequisitions {
        case http200(value: PaginatedRequisitionList, raw: ClientResponse)
        case http400(value: ModelErrorResponse, raw: ClientResponse)
        case http401(value: ModelErrorResponse, raw: ClientResponse)
        case http403(value: ModelErrorResponse, raw: ClientResponse)
        case http404(value: ModelErrorResponse, raw: ClientResponse)
        case http429(value: ModelErrorResponse, raw: ClientResponse)
        case http0(raw: ClientResponse)
    }

    /**
     GET /api/v2/requisitions/
     Retrieve all requisitions belonging to the company
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter limit: (query) Number of results to return per page. (optional, default to 100)
     - parameter offset: (query) The initial zero-based index from which to return the results. (optional, default to 0)
     - returns: `EventLoopFuture` of `RetrieveAllRequisitions` 
     */
    open class func retrieveAllRequisitions(limit: Int? = nil, offset: Int? = nil, headers: HTTPHeaders? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared, beforeSend: @Sendable (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<RetrieveAllRequisitions> {
        return retrieveAllRequisitionsRaw(limit: limit, offset: offset, headers: headers, apiConfiguration: apiConfiguration, beforeSend: beforeSend).flatMapThrowing { response -> RetrieveAllRequisitions in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(PaginatedRequisitionList.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: PaginatedRequisitionList.defaultContentType)), raw: response)
            case 400:
                return .http400(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 401:
                return .http401(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 403:
                return .http403(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 404:
                return .http404(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            case 429:
                return .http429(value: try response.content.decode(ModelErrorResponse.self, using: apiConfiguration.contentConfiguration.requireDecoder(for: ModelErrorResponse.defaultContentType)), raw: response)
            default:
                return .http0(raw: response)
            }
        }
    }
}
