//
// RequisitionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class RequisitionsAPI {

    /**

     - parameter requisitionRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SpectacularRequisition
     */
    open class func createRequisition(requisitionRequest: RequisitionRequest, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> SpectacularRequisition {
        return try await createRequisitionWithRequestBuilder(requisitionRequest: requisitionRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v2/requisitions/
     - Create a new requisition
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter requisitionRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SpectacularRequisition> 
     */
    open class func createRequisitionWithRequestBuilder(requisitionRequest: RequisitionRequest, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<SpectacularRequisition> {
        let localVariablePath = "/api/v2/requisitions/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requisitionRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpectacularRequisition>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path) A UUID string identifying this requisition. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SuccessfulDeleteResponse
     */
    open class func deleteRequisitionById(id: UUID, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> SuccessfulDeleteResponse {
        return try await deleteRequisitionByIdWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /api/v2/requisitions/{id}/
     - Delete requisition and its end user agreement
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this requisition. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SuccessfulDeleteResponse> 
     */
    open class func deleteRequisitionByIdWithRequestBuilder(id: UUID, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<SuccessfulDeleteResponse> {
        var localVariablePath = "/api/v2/requisitions/{id}/"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessfulDeleteResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path) A UUID string identifying this requisition. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Requisition
     */
    open class func requisitionById(id: UUID, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> Requisition {
        return try await requisitionByIdWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v2/requisitions/{id}/
     - Retrieve a requisition by ID
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter id: (path) A UUID string identifying this requisition. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Requisition> 
     */
    open class func requisitionByIdWithRequestBuilder(id: UUID, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<Requisition> {
        var localVariablePath = "/api/v2/requisitions/{id}/"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Requisition>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter limit: (query) Number of results to return per page. (optional, default to 100)
     - parameter offset: (query) The initial zero-based index from which to return the results. (optional, default to 0)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PaginatedRequisitionList
     */
    open class func retrieveAllRequisitions(limit: Int? = nil, offset: Int? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> PaginatedRequisitionList {
        return try await retrieveAllRequisitionsWithRequestBuilder(limit: limit, offset: offset, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /api/v2/requisitions/
     - Retrieve all requisitions belonging to the company
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter limit: (query) Number of results to return per page. (optional, default to 100)
     - parameter offset: (query) The initial zero-based index from which to return the results. (optional, default to 0)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PaginatedRequisitionList> 
     */
    open class func retrieveAllRequisitionsWithRequestBuilder(limit: Int? = nil, offset: Int? = nil, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<PaginatedRequisitionList> {
        let localVariablePath = "/api/v2/requisitions/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "offset": (wrappedValue: offset?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedRequisitionList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
