//
// TokenAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class TokenAPI {

    /**

     - parameter jWTRefreshRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SpectacularJWTRefresh
     */
    open class func getANewAccessToken(jWTRefreshRequest: JWTRefreshRequest, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> SpectacularJWTRefresh {
        return try await getANewAccessTokenWithRequestBuilder(jWTRefreshRequest: jWTRefreshRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v2/token/refresh/
     - Refresh access token
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter jWTRefreshRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SpectacularJWTRefresh> 
     */
    open class func getANewAccessTokenWithRequestBuilder(jWTRefreshRequest: JWTRefreshRequest, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<SpectacularJWTRefresh> {
        let localVariablePath = "/api/v2/token/refresh/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: jWTRefreshRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpectacularJWTRefresh>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter jWTObtainPairRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: SpectacularJWTObtain
     */
    open class func obtainNewAccessRefreshTokenPair(jWTObtainPairRequest: JWTObtainPairRequest, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) async throws(ErrorResponse) -> SpectacularJWTObtain {
        return try await obtainNewAccessRefreshTokenPairWithRequestBuilder(jWTObtainPairRequest: jWTObtainPairRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api/v2/token/new/
     - Obtain JWT pair
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter jWTObtainPairRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<SpectacularJWTObtain> 
     */
    open class func obtainNewAccessRefreshTokenPairWithRequestBuilder(jWTObtainPairRequest: JWTObtainPairRequest, apiConfiguration: GoCardlessClientAPIConfiguration = GoCardlessClientAPIConfiguration.shared) -> RequestBuilder<SpectacularJWTObtain> {
        let localVariablePath = "/api/v2/token/new/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: jWTObtainPairRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpectacularJWTObtain>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
