name: Run Custom Renovate

on:
  schedule:
    - cron: '14 3 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/custom-renovate.yml'


env:
  NODE_VERSION: 22
  PNPM_VERSION: 10.17.0

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Renovate
        uses: actions/checkout@v4
        with:
          repository: dracks/renovate
          ref: feat/adding-package-yaml-support
          persist-credentials: false
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_CLIENT_SECRET }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: ${{ env.PNPM_VERSION }}

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Validate Renovate (PRs, dry-run)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_DRY_RUN: full
        run: pnpm start Dracks/mr-scrooge

      - name: Run Renovate (non-PRs)
        if: ${{ github.event_name != 'pull_request' }}
        env:
          RENOVATE_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: pnpm start Dracks/mr-scrooge