name: Test Server
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
        - main
        - mr-scrooge-3.0.0

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: swift:5.10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: swift test --parallel
        # run: swift test
