# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Test view

on: 
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

env:
  NODE_VERSION: 20
  PNPM_VERSION: 10.7.1

jobs:
  checks:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
            name:
                - type-check
                - lint
                - test
                - build
            include:
                - name: type-check
                  cmd: type-check
                - name: lint
                  cmd: lint
                - name: test
                  cmd: test --coverage
                - name: build
                  cmd: build:view
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: ${{ env.PNPM_VERSION }}

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - run: pnpm install
        name: Install pnpm dependencies
      - run: pnpm run build:typespec
        name: Update openapi from typespec
      - run: pnpm run build:api-models
        name: Update api models
      - run: pnpm run ${{ matrix.cmd }}
      - if: matrix.name == 'test'
        name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
