name: Test Server
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
        - main
        - mr-scrooge-3.0.0

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04-arm
    container: swift:6.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
            path: .build
            key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
            restore-keys: |
                ${{ runner.os }}-spm-
      - name: Run tests
        run: swift test --parallel
        # run: swift test
