name: Test Server
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
        - main
        - mr-scrooge-3.0.0
        - fix/cache
  pull_request:
    branches:
        - main
        - mr-scrooge-3.0.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04-arm
    container: swift:6.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install zstd
        run: |
            apt-get update -y
            apt-get install -y zstd curl
      - uses: actions/cache@v4
        with:
            path: .build
            key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift') }}
      - name: Run tests
        run: swift build --build-tests --enable-code-coverage
  test:
    name: Test
    needs: build
    runs-on: ubuntu-24.04-arm
    container: swift:6.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install zstd
        run: |
            apt-get update -y
            apt-get install -y zstd curl
      - uses: actions/cache@v4
        with:
            path: .build
            key:  ${{ runner.os }}-spm-${{ hashFiles('Package.swift') }}
      - name: Run tests
        run: swift test --parallel --skip-build --enable-code-coverage
      - name: Prepare Coverage
        run:
            llvm-cov export -format="lcov" .build/debug/mr-scroogePackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
      - uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}