# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Test view

on: [pull_request]

env:
  NODE_VERSION: 20

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run test:view
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v4
          name: Install pnpm
          with:
            run_install: false

        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
            node-version: ${{ env.NODE_VERSION }}
            cache: 'pnpm'

        - run: pnpm install
        - run: pnpm run lint
